[package]
name = "optimum_core"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"

[dev-dependencies]
ordered-float = "2.10.0"
