[package]
name = "optimum"
version = "0.0.0"
edition = "2021"
description = "Future Framework to solve optimization problems"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
