[package]
name = "optimum"
version = "0.0.1"
edition = "2021"
description = "Future Framework to solve optimization problems"
license = "GPL-3.0-or-later"
repository = "https://github.com/dbofmmbt/optimum"
keywords = ["metaheuristics", "optimization"]
categories = ["algorithms", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
