[package]
name = "optimum_metaheuristics"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
optimum_core = { path = "../optimum_core" }
rand = "0.8.4"
